apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-v1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: payment-v1
    spec:
      containers:
        - name: payment-v1
          image: camiloromerop/payments-ms:latest    
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "200m"                
          ports:
            - containerPort: 3001
          readinessProbe:
              httpGet: 
               path: / 
               port: 3001  
          livenessProbe:
            httpGet: 
               path: / 
               port: 3001
