apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-v1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-v1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: orders-v1
    spec:
      containers:
        - name: orders-v1
          image: camiloromerop/orders-ms:latest
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "200m"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000